### ISSUE TITLE
File corrupted when using TMongoStream

### ISSUE THREAD

**Issue by waltrick** [stijnsanders/TMongoWire#22]
Hi Sanders,

I have the following situation: 
Upload files in php and downlod in your component, when I do that the file is corrupted.
But when I upload and downlod for its component works correctly. 

Any suggestions?

**Comment by oneidewarrior** [comment]
hi
I have a problem when I upload large files such as videos.
They are losing quality.

So I changed the value of the const 'mongoStreamDefaultChunkSize' for $ E4E1C0, which is equal to 15000000 in decimal. With that the video did not lose more quality.

Same problem happens with images, if I leave the default value of const 'mongoStreamDefaultChunkSize'.

In my view this is not correct because the database is very large. Any suggestion?
