### ISSUE TITLE
ERROR - Download With Java driver

### ISSUE THREAD

**Issue by OneideLuizSchneider** [stijnsanders/TMongoWire#29]
Hi
When uploading XML files with TMongoWire, then download with JAVA, XML returns corrupted with null character.

Detail, TMongoWire with TMongoWire works normally.

Images example.

![erro02](https://cloud.githubusercontent.com/assets/5761239/13867498/2c3d0f1a-ec9e-11e5-8c9f-44a7f06fa5e7.PNG)
![erro01](https://cloud.githubusercontent.com/assets/5761239/13867499/2c3ebd38-ec9e-11e5-9fde-eb2de8df7e67.PNG)
)

**Comment by stijnsanders** [comment]
I don't have access to a Java set-up to confirm that side of things. Could you do these few things, please?

* confirm that the XML file itself doesn't contain a NUL character, either by a binary editor, or with `dir` in a `cmd` window and check it's exactly the expected number of bytes. (Also, does the file contain a 3 byte UTF8 byte order mark header?) I see on your screenshot Notepad++ is set to "Dos\Windows ANSI" so that is probably not the case.
* use mongo shell and query the document in the `testes.files` for this file? I'm interested in the `length` field.
* delete the file, add the file with TMongoWire, query the files document, then delete it, add it with java and query the files document. If anything there is different I can get to the cause of the problem faster, if it's identical, I would like to see the `testes.chunks` documents as well.

**Comment by stijnsanders** [comment]
Found it! Apparently `VarArrayRedim` takes the new _upper bound_ and not the new _array length_. Please see my recent commit that fixes this.

**Comment by OneideLuizSchneider** [comment]
Hi
Yes, now it worked.
Thank you.
