### ISSUE TITLE
Number To Return

### ISSUE THREAD

**Issue by scaleman114** [stijnsanders/TMongoWire#37]
Would it be possible to show an example with the NumberToReturn property? I don't seem to be able to get it to work.
When I set WireQuery.NumberToReturn := 2; 
It seems to make no difference.

**Comment by stijnsanders** [comment]
This may have changed since I created the NumberToReturn property:
https://docs.mongodb.com/manual/reference/mongodb-wire-protocol/#op-query
Apparently, if you set the property to a negative value, the cursor will be closed after that number.
If you set it to a positive number, the _first response_ to the query will be limited to this number of documents. Depending on the average size of documents this _may_ speed up getting this first set of documents, but the cursor will stay open and `TMongoWireQuery.Next` will just perform as expected and pullin more documents after that, if there are more available.
Does that answer your question?

**Comment by scaleman114** [comment]
Yes that answers my question. Many thanks for your help.
